name: ci-cd

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish 
      run: dotnet publish -c Release --no-build -o publishoutput
    - name: Inject slug/short variables  
      uses: rlespinasse/github-slug-action@v3.x
    - name: Upload artifact
      if: success()  
      uses: actions/upload-artifact@v2  
      with:  
        name: ${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}  
        path: ./publishoutput

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      - name: Download artefact
        uses: actions/download-artifact@v1
        with:
          name: ${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}
      - name: Publish to Netlify
        uses: netlify/actions/cli@master
        env:
            NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
            NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
            args: deploy --dir=${{ env.GITHUB_REF_SLUG }}-${{ github.run_id }}-${{ github.run_number }}/wwwroot --prod
            secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'